### ISSUE TITLE
Nonetype object is not iterable

### ISSUE THREAD

**Issue by norbit58** [km2ii/JVP_TG-PLUS#105] opened 2023-02-01 23:37 UTC
![error](https://user-images.githubusercontent.com/124216509/216192132-df40e114-765c-4bfe-8d6e-340aba8523d6.PNG)
I get this every time I try to run Configtools. Any suggestions? Thanks.

**Comment by km2ii** [comment] 2023-02-02 12:38
This bug caused by not installing veai, fixed in the next version.

**Closed** 2023-02-04 05:17 UTC
